function [population,it] = myGA(f,V,M,lb,ub)
	% myGA(f,V,M,lb,ub)
	% f : function to minimize
	% V : Dimension of the search space.
	% M : Number of objectives.
	% lb = lower bound vector.
	% ub = upper bound vector. 

	%% DEFINITION OF THE PARAMETERS

	N = 100;    % Population size
	NP = 40;    % Size of the mating pool
	NC = 30;    % Number of children generated by generation
    % MUST BE EVEN
    assert(mod(NC,2) == 0)
	P = 0.5;     % probability of recombination

	verbose = true; % (true) plots each iteration

	%% GENETIC ALGORITHM

	% Generation of the intial population
	population = initPopulation(N,V);

	population = evaluatePopulation(population,f,N,V,M,lb,ub);

	population = sortPopulation(population,V,M);

	% Main loop
	it = 1;

	runFlag = true;
	while runFlag
        
		parents = selectionTournament(population,NP,V,M);	
        %size(parents)

		offspring = geneticOperators(parents,f,N,NC,P,V,M,lb,ub);
        
		population = [ population(:,1:V+M) ; offspring(:,1:V+M) ];

		population = sortPopulation(population,V,M);
        population(:,1:(V+M))

		population = cropPopulation(population,N);

		% Visualization
		if verbose
			illustratePopulation(population,V,M,lb,ub,it);
			drawnow;
			pause(0.1);
		end

		it = it+1;

		runFlag = stopCriterion(it);
    end
	
end
